//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteUtilisateur
    {
        public CompteUtilisateur()
        {
            this.Connexion = new HashSet<Connexion>();
        }
    
        public int IdUtilisateur { get; set; }
        public string NomUtilisateur { get; set; }
        public string Login { get; set; }
        public string MotDePasse { get; set; }
        public System.DateTime DateCreationCompte { get; set; }
        public bool Actif { get; set; }
        public string CodeProfil { get; set; }
    
        public virtual Profil Profil { get; set; }
        public virtual ICollection<Connexion> Connexion { get; set; }
    }
}
