//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int IdFacture { get; set; }
        public System.DateTime DateFacture { get; set; }
        public double Montant { get; set; }
        public double RestePlafond { get; set; }
        public int IdPlafond { get; set; }
        public int IdPolice { get; set; }
        public int IdAdherent { get; set; }
        public int IdAffilie { get; set; }
        public int IdPrestataire { get; set; }
    
        public virtual Adherent Adherent { get; set; }
        public virtual Affilie Affilie { get; set; }
        public virtual Plafond Plafond { get; set; }
        public virtual Police Police { get; set; }
        public virtual Prestataire Prestataire { get; set; }
    }
}
