//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Police
    {
        public Police()
        {
            this.Adherent = new HashSet<Adherent>();
            this.Facture = new HashSet<Facture>();
            this.Ligne_PolicePlafond = new HashSet<Ligne_PolicePlafond>();
        }
    
        public int IdPolice { get; set; }
        public string LibellePolice { get; set; }
    
        public virtual ICollection<Adherent> Adherent { get; set; }
        public virtual ICollection<Facture> Facture { get; set; }
        public virtual ICollection<Ligne_PolicePlafond> Ligne_PolicePlafond { get; set; }
    }
}
