//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestataire
    {
        public Prestataire()
        {
            this.Facture = new HashSet<Facture>();
        }
    
        public int IdPrestataire { get; set; }
        public string NomOuRaisonSociale { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Adresse { get; set; }
        public int IdPlafond { get; set; }
    
        public virtual ICollection<Facture> Facture { get; set; }
        public virtual Plafond Plafond { get; set; }
    }
}
