//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil
    {
        public Profil()
        {
            this.CompteUtilisateur = new HashSet<CompteUtilisateur>();
        }
    
        public string CodeProfil { get; set; }
        public string NomProfil { get; set; }
    
        public virtual ICollection<CompteUtilisateur> CompteUtilisateur { get; set; }
    }
}
